# Generated by Django 3.2.4 on 2022-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advision',
            name='desciption',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advision',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
